# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        poolset:
            properties:
                id: ~
                name: { boost: 5 }
                mappools:
                    type: "object"
                    properties:
                        name: { boost: 2 }
                contributors:
                    type: "object"
                    properties:
                        user:
                            type: "object"
                            properties:
                                name: { boost: 10 }

            persistence:
                driver: orm
                model: App\Entity\PoolSet
