vich_uploader:
    db_driver: orm

    mappings:
        cover:
            # alias qui nous permet d'accéder à nos images depuis le navigateur
            uri_prefix: /images/cover
            # Chemin vers le dossier de stockage
            upload_destination: '%kernel.project_dir%/public/uploads/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    